config/routes.rb
Rails.application.routes.draw do
 #resources 'shared/beaches'

  devise_for :users

  resources :beaches, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:edit, :update, :show, :destroy]

  root to: 'beaches#index'
  get 'dashboard', to: 'pages#dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beach.rb
class Beach < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  include PgSearch::Model
  pg_search_scope :search_by_title_and_syllabus,
    against: [:name, :location],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :beach
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :beaches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # before_action :configure_permitted_parameters, if: :devise_controller?
  # include Pundit
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # # def configure_permitted_parameters
  # #   # For additional fields in app/views/devise/registrations/new.html.erb
  # #   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

  # #   # For additional in app/views/devise/registrations/edit.html.erb
  # #   devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  # # end
  # private

  # def skip_pundit?
  #   devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  # end
end

app/controllers/beaches_controller.rb
class BeachesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR location ILIKE :query"
      @beaches = Beach.where(sql_query, query: "%#{params[:query]}%")
    else
      @beaches = Beach.all
    end
  end

  def show
    @beach = Beach.find(params[:id])
    @booking = Booking.new
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @beach = Beach.find(params[:beach_id])
  end

  def create
    @beach = Beach.find(params[:beach_id])
    @booking = Booking.new(bookings_params)
    @booking.user = current_user
    @booking.beach = @beach
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  # def show
  #   @booking = Booking.find(params[:id])
  # end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path
  end

  def edit
    @booking = Booking.find(params[:id])
    @beach = @booking.beach
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(bookings_params)
      redirect_to dashboard_path
    else
      render :new
    end
    # @booking.start_date = params.
  end

  private

  def bookings_params
    params.require(:booking).permit(:start_date, :end_date, :beach_id)
    # if @booking.update(params[:booking].permit(:client_id, :start_time, :length))
    #   flash[:notice] = 'Your booking was updated succesfully'
    # else
    #   render 'edit'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 skip_before_action :authenticate_user!, only: :home
 def home
 end
 def index
   @bookings = Booking.all
 end
 def dashboard
  # @beach = Booking.find(params[:beach_id])
   @bookings = current_user.bookings
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beaches/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://imageresizer.static9.net.au/NzJ7oBU3G7O68jCxihefvyWFwxo=/1200x0/http%3A%2F%2Fprod.static9.net.au%2F_%2Fmedia%2F2018%2F06%2F12%2F15%2F16%2FTop-10-most-expensive-beaches-in-the-world.jpg);">
  <div class="container">
    <h1>Have a break-<strong> rent a beach</strong>!</h1>
    <p>Change your routine and get an organic tan with one of our beaches around the world.</p>
    <div class="search" style="width: 90%">
    <%= form_tag beaches_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a Beach"
  %>

          <%= submit_tag "Search now", class:"btn btn-flat"    %>
</div>
<% end %>

  </div>
</div>

<div class="container">
  <div class="row">
   <% @beaches.each do |beach| %>
    <div class="col-xs-12 col-md-4">
      <div class="card-trip">
        <img src= <%= beach.photo %> />
          <div class="card-trip-infos">
           <h2><%= beach.name %></h2>
           <p><%= beach.description %></p>
            <div class="price-info">
           <strong>Rent per day:</strong>
           <p><%= beach.rent_per_day %>€</p>
            </div>
          </div>
    <%= link_to "", beach_path(beach), class: "card-link"%>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/beaches/show.html.erb
<div class="container">
  <div class="row">
    <div class="card-product">
      <div class="col-xs-12 col-md-4">
        <div class ="card-product img">
        <img src= <%= @beach.photo %> />
        </div>
      </div>

    <div class="col-xs-12 col-md-4">
      <div class="card-product-infos">

        <h1><strong> <%= @beach.name %></h1></strong>

         <p><%= @beach.description %></p>

         <p> <strong>Location:</strong>
         <%= @beach.location %></p>

         <p> <strong>Rent per day:</strong>
         <%= @beach.rent_per_day %> €</p>
      </div>
    </div>

      <div class="col-xs-12 col-md-4">


        <h1>Book your beach at:</h1>
        <%= @beach.name %></p>
          <%= simple_form_for [@beach, @booking] do |f| %>
          <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.submit "Book me now", class: "btn btn-warning" %>
          <%= link_to 'Go back', beaches_path, class: "btn btn-warning"   %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="card-product">
      <div class="col-xs-12 col-md-4">
        <div class ="card-product img">
        <img src= <%= @beach.photo %> />
        </div>
      </div>

    <div class="col-xs-12 col-md-4">
      <div class="card-product-infos">

        <p> <strong>Name:</strong>
        <%= @beach.name %></p>

         <p> <strong>Description:</strong>
         <%= @beach.description %></p>

         <p> <strong>Location:</strong>
         <%= @beach.location %></p>

         <p> <strong>Rent per day:</strong>
         <%= @beach.rent_per_day %> €</p>
      </div>
    </div>

      <div class="col-xs-12 col-md-4">
        <h1>Change Booking</h1>
        <%= simple_form_for [@booking]  do |f| %>
          <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.submit "Save Changes", class: "btn btn-primary" %>
          <%= link_to 'Cancel', dashboard_path, class: "btn btn-warning"   %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<!-- /<h1>New Booking</h1>

<%= simple_form_for [@beach, @booking] #do |f| %>
  <%= f.input #:start_date %>
  <%= f.input #:end_date %>
  <%= f.submit #{}"Book me now", class: "btn btn-primary" %>
<% #end %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BookyourBeach</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>


    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1>Your Bookings</h1>

    <% @bookings.each do |booking|  %>
    <div class="card-product2">
    <%= image_tag booking.beach.photo %>
<div class="card-product-infos2">
      <strong><%= booking.beach.name %></strong>
      <strong>From:</strong>
      <h6> <%= booking.start_date %> </h6>
      <strong>To:</strong>
      <h6> <%= booking.end_date %> </h6>

      <h6> Number of days: </h6><% number_of_days = (booking.end_date - booking.start_date + 1).to_i %>
      <h6 class="card-trip-pricing"><%= number_of_days %></h6>
    <%= link_to "Make changes", edit_booking_path(booking), class: 'btn btn-warning' %>
    <%= link_to booking_path(booking), class: 'btn btn-warning', method: :delete, data: { confirm: "Are you sure?" } do %>
      <p> Cancel </p>
      <% end %>
      </div>
    </div>
    <% end %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_card.html.erb
<!-- <div class="cards">

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),  url('https://images.unsplash.com/photo-1504532724559-22878efd533a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80')">

</div>


  <div><div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),  url('https://images.unsplash.com/photo-1504532724559-22878efd533a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80')">

    Indonsia
  </div>
</div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1506&q=80')">
    Newsland
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1504532724559-22878efd533a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1534&q=80')">
    Italy
  </div>
</div>
 -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <div class="footer">
  <div class="footer-links">
    <a href="https://www.github.com/" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://www.twitter.com/" target="_blank"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/" target="_blank"><i class="fab fa-linkedin"></i></a>

  </div>
  <p style="color: black">All Rights Reserved for Le Wagon Berlin Germany © 2019</p>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to beaches_path, class: "navbar-brand" do %>
    <i class="fas fa-umbrella-beach"></i>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <li class="nav-item">

          <%= link_to "Home", beaches_path, class: "nav-link"   %>

        </li>
        <li class="nav-item">
          <%= link_to "Bookings", dashboard_path, class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">
          <%= image_tag "https://images.unsplash.com/photo-1437719417032-8595fd9e9dc6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1267&q=80", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Sign up", "beaches", class: "dropdown-item" %>
            <%= link_to "Sign in", "#", class: "dropdown-item" %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>